const ROOT_PRODUCTS = document.getElementById('products')
const ROOT_HEADER = document.getElementById('header')
const ROOT_SHOP = document.getElementById('shop')
const ROOT_CARTHEAD = document.getElementById('carthead')
const ROOT_FOOTER = document.getElementById('footer')